# Outputting
permalink: /:categories/:year/:month/:day/:title.html
date_locale: tr
# Conversion
markdown:         kramdown

excerpt_separator: <!--more-->

# Config for your profile.
title:            kKerem            # Site title
name:             Kerem Er            # Your name
avatar:           /theme/img/logo.png   # Path to an avatar image

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
# Use "" when runnign the site out of the root of a domain.

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the docs into a collection.
collections:
  docs:
    output: true
    title: Docs
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
      layout: defaults/portfolio
  -
    scope:
      path: "_docs"
    values:
      show_profile: false
      layout: defaults/docs
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list


url: "https://kkerem.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-date-localization
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-lazy-load-image
  - jekyll-imagemagick

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d %b, %y'

lazy_load_image:
  src_attr_name: data-src # [required] You need to specify the attributes to be saved for lazy loading
  class_attr_values: # [optional] if you want to add custom class value, please add values
    - lazyload
  ignore_selectors: # [optional] if you want to ignore applying lazy load image, please add selector (css or xpath)
    - ".ignore-lazy-image-load"
    - "/*[@class='ignore-lazy-image-load']"
  additional_attrs: # [optional] if you want to add attributes, please add key value
    "data-size": auto


imagemagick:
  enabled: true
  widths:
    - 1024
    - 512
    - 0
  input_directories:
    - /uploads
  input_formats:
    - ".png"
    - ".tiff"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 100%"

thumbnails:
  preview:
    width: 360
    height: 220
  sidebar:
    width: 80
    height: 80

picture:
  ignore_missing_images: true